server:
  port: 8087
github:
  Client:
    id: bedef8cad503139674a5
    secret: f3d7228b93ee8cc281138b03aa7fca16a6091e6a
  redirect:
    url: http://129.211.64.121:8087/callback
spring:
  datasource:
    url: jdbc:mysql://129.211.64.121:3306/community?userSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver